In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

import numpy as np

In [3]:
np.set_printoptions(linewidth=200)

In [4]:
w = np.ones(10) * 0.5
d_g = np.array([[1, -1]] * 10)

hat_mu = np.arange(20).reshape(10, 2)

d_g

array([[ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1]])

In [5]:
(hat_mu / np.array([w, w]).T).T

array([[ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 2.,  6., 10., 14., 18., 22., 26., 30., 34., 38.]])

In [13]:
np.sum(d_g * (hat_mu / np.array([w, w]).T), axis=1)

array([-2., -2., -2., -2., -2., -2., -2., -2., -2., -2.])

In [41]:
np.dot(np.arange(10).reshape(5, 2), np.arange(2).reshape(2))

array([1, 3, 5, 7, 9])

In [44]:
import cvxpy as cvx

In [47]:
agent_num = 10

a = np.ones(10)
b = np.ones(10)
c = np.ones(10)

In [50]:
x = np.ones(10)

a @ np.square(x) + b @ x + np.sum(c)

30.0

In [57]:
x = cvx.Variable(agent_num)
objective = cvx.Minimize(a @ cvx.square(x) + b @ x + np.sum(c))
constraints = [x_lower <= x, x <= x_upper]

problem = cvx.Problem(objective, constraints)
problem.solve()

47534.0

In [52]:
constraint_set_upper: tuple[int] = (300, 350)
constraint_set_lower: tuple[int] = (50, 80)

x_upper = np.random.randint(*constraint_set_upper, agent_num)
x_lower = np.random.randint(*constraint_set_lower, agent_num)

array([303, 349, 341, 311, 301, 331, 313, 303, 343, 314])

In [60]:
from itertools import cycle
from tqdm import tqdm

In [63]:
for i, j in enumerate(tqdm(cycle(range(1, 10)), total = 30)):
    if i > 20:
        break
    print(j)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                 | 21/30 [00:00<?, ?it/s]

1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
